# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bing Wang
title: Associate Lecturer in Univerity of New South Wales Canberra
email: bing.wang@adfa.edu.au
website: https://github.com/arielBWong

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  arielBWong
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: bing_in_r7
# linkedin_username:
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name's Bing Wang. I am currently working as a research associate in MDO group School of Engineering and Information Technology, University of New South Wales, Canberra. 
  My research interests are evolutionary optimization, data mining and agent system. My current focus is on designing algorithms for solving expensive bilevel optimization problems.
  I am interested in incorporating machine learning techniques especially knowledge transfer into optimization process. My past research experiences include agent system, 
  social network analysis, medical image process and natural language processing. I am fortunate to have worked with many interesting and inspiring scholars in these projects,
  and the experiences have positioned me to be able to see research questions from a wide range of directions. 

content:
  # - title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #        #   icon: fab fa-github
  #        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNSW Canberra
        link: https://research.unsw.edu.au/people/dr-bing-wang
        # link_text: boringcompany.com
        sub_title: Associate Lecturer
        caption: October 2019 - Present
        quote: >
          everything is optimization
        description: | # this will include new lines to allow paragraphs
            Expensive problems refer to optimization problems wherein evaluation of each solution can incur significant cost, either in the form of computation time or 
            financial investment. For such problems, it is important to control the number of evaluations while searching for optimal solutions. In this work, we look into 
            techniques like surrogate modelling and knowledge transfer to assist search  in controlling cost. 
      
      - layout: left
        title: Chinese Academy of Sciences
        link: 
        # link_text: boringcompany.com
        sub_title: Postdoc, Associate professor
        caption: May 2015 - October 2019
        quote: >
            Understand human
        description: | # this will include new lines to allow paragraphs
            Social media has become a big part of people's day to day life. How to analyse the dynamic of social media open a series of interesting research questions. 
            We ustilize tools like graph analysis, natual language process to study natural community of social network, influence of KOLs, and Sentiment of users responding to events.

      - layout: left
        title: UNSW Canberra
        link: 
        # link_text: boringcompany.com
        sub_title: Ph.D project
        caption: August 2011 - March 2014
        quote: >
            make sense of world from the eyes of agent 
        description: | # this will include new lines to allow paragraphs
            Without any prior knowledge, how could an artifical agent work out causal relations among its sensing data? In this project, we rely on association rule mining and
            neural netowrk to design a inference mechanism for artifical agent, so that it can learn to build a causal knowledge network from its observation. 


      - layout: left
        title: UNSW Sydney
        link: 
        # link_text: boringcompany.com
        sub_title: Ph.D project
        caption: September 2009 - July 2011
        quote: >
            brain is interesting 
        description: | # this will include new lines to allow paragraphs
            Brain is mysterious. MRI techniques open a window for us to peek it. In this project, we use hidden Markov model to build an brain age estimator for assisting 
            doctors diagose mild cognitive impairment. Later development of this technqiue was purchased and adopted in a commercial hospital systems. 


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNSW Canberra
        caption: 2009 - 2014
        sub_title: Doctor of Philosophy (Ph.D), Computer Science
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Thesis title
          - Autonomous hypothesis generation for knowledge discovery in continuous domains
          
          Supervisor
          - Prof. Hussein A. Abbass
          - Prof. Kathryn E. Kasmarik

      - layout: left
        title: Ocean University of China
        caption: 2006 - 2009
        sub_title: Master of Engineering, Control theory and control engineering
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Thesis title
          - Video compression algorithm for underwater acoustic channel transmission
          
          Supervisor
          - Prof. Qingzhong Li

      - layout: left
        title: Ocean University of China
        caption: 2002 - 2006
        sub_title: Bachelor of Engineering, Automation
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          UG project
          - Software development for mobile robot motion control based on intelligent PID
          
          Supervisor
          - Prof. Qingzhong Li


  - title: Fundings
    layout: text
    content: | # this will include new lines to allow paragraphs
      I have secured a list of fundings from both industry and academic funding agencies
      - Self forming research group, School of Engineering and Information Technology, UNSW Canberra 2021 (Collaborative)
      - Institute of acoustics, Chinese academy of Sciences, Young Elite Research Project. 2018 (PI)
      - Longleding technology, Brain imaging analysis software. 2017 (PI)
      - Foundation of Science and technology on Information Assurance Laboratory, KJ-17-102. 2017 (PI)
      - Chinese Academy of Sciences intenational Postdoctoral exchange fellowship program. 2016 (PI)
      - China Postdoctoral science foundation grant 2015LH0041. 2015 (PI)

  - title: Services
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Supervision, I have involved in HDR supervision of 6 students who are graduated. I am currently supervising UG project: data driven expensive optimization methods
      - IEEE Computational intelligence society, ACT chapter. Executive commitee 2021 - present
      - UNSW Canberra, yound women in engineering program, robot team.  2019-2022

      
  - title: Selected publication
    layout: text
    content: | # this will include new lines to allow paragraphs
      - B. Wang, H. Singh, T. Ray. Investigating Neighborhood Solution Transfer Schemes for Bilevel Optimization, WCCI 2022
      - B. Wang, Hemant K. Singh, T. Ray. Adjusting normalization bounds to improve hypervolume based search for expensive multi-objective optimization. Complex Intell. Syst. (2021)
      - B. Wang, Singh HK, Ray T. Investigating Normalization Bounds for Hypervolume-Based Infill Criterion for Expensive Multiobjective Optimization. In Evolutionary Multi-Criterion Optimization: 11th International Conference, EMO 2021
      - B. Wang, Singh, H.K. and Ray, T., Bridging Kriging believer and expected improvement using bump hunting for expensive black-box optimization. In Proceedings of the Genetic and Evolutionary Computation Conference, GECCO 2021.
      - B. Wang, Singh, H.K. and Ray, T., Comparing expected improvement and Kriging believer for expensive bilevel optimization, in Proceedings of IEEE Congress on Evolutionary Computation, CEC 2021.
      - Manshu Tu, Bing Wang. Adding Prior Knowledge in Hierarchical Attention Neural Network for Cross Domain Sentiment Classification. IEEE Access. vol.7, 2019.
      - Junqing He, Bing Wang, Mingming Fu, Tianqi Yang, Xuemin Zhao. Hierarchical Attention and Knowledge Matching Networks With Information Enhancement for End-to-End Task-Oriented Dialog Systems. IEEE Access. vol. 7. 2019.
      - Manshu Tu, Bing Wang, Xunmin Zhao. Chinese Dialogue Intention Classification Based on Multi-Model Ensemble. IEEE Access. vol. 7. 2018.
      - Taisong Li, Bing Wang, Yasong Jiang, Yan Zhang, Yonghong Yan. Restricted Boltzmann Machine-Based Approaches for Link Prediction in Dynamic Networks. IEEE Access. vol. 6. 2018.
      - B. Wang, K. Merrick, H. Abbass. Cooperative Co-Evolutionary Neural Networks for Mining Functional Association Rules. IEEE transactions on neural networks and learning system. 2016
      - B. Wang, K. Merrick, H. Abbass. Autonomous Hypothesis Generation as an Environment Learning Mechanism for Agent Design. Artificial Life and Computational Intelligence Lecture Notes in Computer Sciences. vol. 8955, pp. 210-225, 2015.
      - B. Wang, T. Pham. MRI-based age prediction using hidden Markov models. Journal of neuroscience methods. vol. 199, no.1, 2011.
      - T. Pham, F. Salvetti, B. Wang, and others. The hidden-Markov brain: comparison and inference of white matter hyperintensities on magnetic resonance imaging (MRI). Journal of Neural Engineering. vol. 8, no. 1, 2011.

  
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
